spring:
    profiles:
    active: dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-alec.dev
---       
spring:
    profiles: test
    application:
        name: microservicecloud-config-alec.test